# Generated by Django 3.2.16 on 2023-02-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=510, unique=True)),
                ('firstname', models.CharField(max_length=255, unique=True)),
                ('middlename', models.CharField(max_length=255, unique=True)),
                ('lastname', models.CharField(max_length=255, unique=True)),
                ('parent_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
